### PR TITLE
Add MapEffect and DisposableMapEffect

### PR DESCRIPTION
**Pull request by rinlv**
1. Add MapEffect and DisposableMapEffect.
2. Add an example on `MainActivity` of `annotation-simple` using MapEffect and DisposableMapEffect.

### CODE REVIEW

**Comment by rinlv** [comment]
@JonasVautherin please take a look, and pump the new version

**Review by JonasVautherin — COMMENTED** [review]
Thanks for the contribution!

I am wondering, though: what is the difference between using `MapEffect` and `DisposableMapEffect`, versus improving our current [`MapProperties`](https://github.com/ramani-maps/ramani-maps/blob/main/ramani-maplibre/src/main/java/org/ramani/compose/MapProperties.kt)?

For instance, you can already set the max zoom in the MapProperties, and it will be applied [here](https://github.com/ramani-maps/ramani-maps/blob/main/ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt#L175). We could certainly add `minZoom` to `MapProperties` this way, right?

If I understand correctly, another use for `MapEffect`/`DisposableMapEffect` is to access the underlying `MapLibreMap` object, right? Isn't it sufficient to do it like in [this example](https://github.com/ramani-maps/ramani-maps/blob/main/examples/custom-annotation/app/src/main/java/org/ramani/example/custom_annotation/ProgressCircle.kt#L34)?

```
val mapApplier = currentComposer.applier as MapApplier
```

Thanks in advance for your insights!

**Comment by rinlv** [comment]
1. Yes, we can set max/min zoom via `MapProperties`. I just made a simple example with the new method.
2. You are right about another use of `MapEffect`/`DisposableMapEffect`. I just want to add other options to access the underlying `MapLibreMap` object. It is good for accessing `MapLibreMap` with conditions via `key` parameter, in my case is ON/OFF following user when the user's location changes.

**Comment by JonasVautherin** [comment]
Is it coming from Mapbox' [MapEffect](https://github.com/mapbox/mapbox-maps-android/blob/main/extension-compose/src/main/java/com/mapbox/maps/extension/compose/MapEffect.kt) and [DisposableMapEffect](https://github.com/mapbox/mapbox-maps-android/blob/main/extension-compose/src/main/java/com/mapbox/maps/extension/compose/DisposableMapEffect.kt)? I wonder how it looks w.r.t. copyright (Mapbox is not open source) 🤔. Would it count as "fair use"?

Still I am not completely sure I understand why it is needed in the library, because you can totally keep it outside of it. Is it so common a use-case that it should be included by default?

**Comment by rinlv** [comment]
> Is it coming from Mapbox' [MapEffect](https://github.com/mapbox/mapbox-maps-android/blob/main/extension-compose/src/main/java/com/mapbox/maps/extension/compose/MapEffect.kt) and [DisposableMapEffect](https://github.com/mapbox/mapbox-maps-android/blob/main/extension-compose/src/main/java/com/mapbox/maps/extension/compose/DisposableMapEffect.kt)? I wonder how it looks w.r.t. copyright (Mapbox is not open source) 🤔. Would it count as "fair use"?
> 
> Still I am not completely sure I understand why it is needed in the library, because you can totally keep it outside of it. Is it so common a use-case that it should be included by default?

Yep, it was inspired by Mapbox. But my bad, `MapEffect` and `DisposableEffect` seem like they are not working with your `MapLibre` when `block` does not trigger when the `key` is changed. So, let me revert them.

**Pull request closed without merging**
