### PR TITLE
feat(styleUrl): add support for dynamic styleUrls

### LINKED ISSUE #73: Support switching between different map styles
Support changing map style on demand -> https://docs.mapbox.com/android/legacy/maps/examples/use-default-styles/

I think this may be unimplemented, but changing the `styleUrl` does not update the map to the new style string.

### PR DESCRIPTION
**Pull request by torrybr**
Support dynamic style urls as described in https://github.com/ramani-maps/ramani-maps/issues/73

I could use some help deciding how best to optimize for performance since changing the `styleUrl` should not reload everything in this `LaunchedEffect` .. im just a little unsure how to create a separate effect that only calls `map.setStyle(styleUrl)`

Resolves #73

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Won't this essentially reload the whole map object? How different is it from just discarding the `MapLibre()` composable and rendering it again?

> I could use some help deciding how best to optimize for performance

Isn't there a way in MapLibre to `.setStyle()` instead of reloading everything? I guess this would be more efficient, right?

**Comment by torrybr** [comment]
yes you are correct! Calling `.setStyle()` on a `styleUrl` change will work without having to rebuild the object.  Would something like below be viable? 

```
    LaunchedEffect(currentStyleUrl) {
            val maplibreMap = map.awaitMap()
            maplibreMap.setStyle(currentStyleUrl)
    }
```

**Comment by JonasVautherin** [comment]
I assume this works, but... I don't know it feels weird to use a LaunchedEffect for that. Did you try doing it in the `MapUpdater`? That would feel a bit more natural to me, if it works.

Would you mind giving it a shot? If nothing else works I guess we can go with the LaunchedEffect, it's fairly small anyway.

**Comment by torrybr** [comment]
Updated to make use of the `MapUpdater` function, is this what you were thinking?? This works as well!

**Comment by JonasVautherin** [comment]
Yeah that looks better! I'll test it ASAP and then we can merge it :+1: :blush:

**Comment by torrybr** [comment]
Thank you for the help and quick responses! Im excited to keep building off this library

**Comment by torrybr** [comment]
Checking back in on this?

**Review by JonasVautherin — APPROVED** [review]
Works for me! Thanks a lot! :rocket:

**Pull request merged**
