### PR TITLE
Support `addOnMapLongClickListener`

### PR DESCRIPTION
**Pull request by torrybr**
Add support for `addOnMapLongClickListener` callback with a new function parameter `onMapLongClick`

### CODE REVIEW

**Comment by torrybr** [comment]
Or does this belong in the `MapUpdater` function?

**Comment by JonasVautherin** [comment]
> Or does this belong in the MapUpdater function?

I need to have a closer look, but: have you tried updating the callback? Does it work?

**Comment by torrybr** [comment]
What callback specifically?

**Comment by JonasVautherin** [comment]
My mistake, I misread it. Can you add a line regarding the new parameter `onMapLongClick` in the documentation (the javadoc above the function)?

**Comment by torrybr** [comment]
Updated! Would you like me to update any examples to showcase this functionality?

**Review by JonasVautherin — APPROVED** [review]
Thank you!

**Pull request merged**
