### PR TITLE
fix: await set style

### PR DESCRIPTION
**Pull request by torrybr**
This should fix error outlined in https://github.com/ramani-maps/ramani-maps/issues/105

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Wait, does it mean that sometimes the callback of `setStyle` is called multiple times, and _before_ it is fully loaded? :open_mouth:

**Comment by torrybr** [comment]
Im not sure this is the end all be all to this issue, but this does solve the crashing for me

**Comment by JonasVautherin** [comment]
I really don't understand why this would have any effect at all. I have never seen this callback being triggered when `style.isFullyLoaded` is not true :thinking:. Are you really sure it consistently fixes #105? I still haven't been able to reproduce...

**Comment by torrybr** [comment]
Let me get you a fully reproducible snippet so I can better articulate whats happening, give me a day or 2 and we can revisit this change.

**Comment by JonasVautherin** [comment]
I'll close this because I think I merged fixes for #105. Feel free to reopen if you realise that it's not the case :+1:.

**Pull request closed without merging**
